<a href="https://colab.research.google.com/github/rajma1/Savedmodels/blob/main/CNN93.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
test_dir = '/content/drive/MyDrive/CELLSFINA/TEST'

In [ ]:
model = tf.keras.models.load_model('/content/drive/MyDrive/Malaria Predictor.h5')

In [ ]:
import tensorflow
import tensorflow.keras
from tensorflow.keras.preprocessing.image import ImageDataGenerator
image_gen = ImageDataGenerator( height_shift_range=0.1, zoom_range=0.2 ,rotation_range=20,
    width_shift_range=0.2,
    horizontal_flip=True,
    shear_range = 0.1,
    fill_mode ='nearest'
    
 )

In [ ]:
test_gen = image_gen.flow_from_directory(directory=test_dir ,
                                          target_size=(130,130), color_mode='rgb',
                                        class_mode='binary', batch_size=16 , shuffle=False  )

Found 2000 images belonging to 2 classes.


In [ ]:
models = model.evaluate(test_gen)

125/125 [==============================] - 30s 238ms/step - loss: 0.1826 - accuracy: 0.9385


In [ ]:
predict = model.predict(test_gen)

125/125 [==============================] - 88s 704ms/step


In [ ]:
predict

array([[1.1941998e-02],
       [4.7730659e-03],
       [1.2865345e-04],
       ...,
       [9.1783583e-01],
       [9.6181661e-01],
       [9.5032972e-01]], dtype=float32)

In [ ]:
predict = predict>0.80
predict

array([[False],
       [False],
       [False],
       ...,
       [ True],
       [ True],
       [ True]])

In [ ]:
test_gen.class_indices

{'Parasitized': 0, 'Uninfected': 1}

In [ ]:
y_test = test_gen.labels
y_test

array([0, 0, 0, ..., 1, 1, 1], dtype=int32)

In [ ]:
from sklearn.metrics import confusion_matrix , classification_report

In [ ]:
print(confusion_matrix(y_test, predict))

[[953  47]
 [ 69 931]]
