<a href="https://colab.research.google.com/github/rajma1/Savedmodels/blob/main/CNN95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Model, load_model

In [ ]:
test_path = '/content/drive/MyDrive/CELLSFINA/TEST'

In [ ]:
image_shape = (130,130,3)

In [ ]:
image_gen = ImageDataGenerator(rotation_range=20, # rotate the image 20 degrees
                               width_shift_range=0.10, # Shift the pic width by a max of 5%
                               height_shift_range=0.10, # Shift the pic height by a max of 5%
                               rescale=1/255, # Rescale the image by normalzing it.
                               shear_range=0.1, # Shear means cutting away part of the image (max 10%)
                               zoom_range=0.1, # Zoom in by 10% max
                               horizontal_flip=True, # Allo horizontal flipping
                               fill_mode='nearest' # Fill in missing pixels with the nearest filled value
                              )

In [ ]:
test_image_gen = image_gen.flow_from_directory(test_path,
                                               target_size=image_shape[:2],
                                               color_mode='rgb',
                                               batch_size=16,
                                               class_mode='binary',shuffle=False)

Found 2000 images belonging to 2 classes.


In [ ]:
model=load_model('/content/malaria_detector (1)cnn.h5')

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
import itertools
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [ ]:
model.evaluate_generator(test_image_gen)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: `Model.evaluate_generator` is deprecated and will be removed in a future version. Please use `Model.evaluate`, which supports generators.
  """Entry point for launching an IPython kernel.


[0.16686737537384033, 0.9549999833106995]

In [ ]:
pred_probabilities = model.predict_generator(test_image_gen)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  """Entry point for launching an IPython kernel.


In [ ]:
pred_probabilities

array([[2.8771837e-03],
       [5.7580992e-06],
       [2.4660176e-02],
       ...,
       [9.5748246e-01],
       [9.5838732e-01],
       [9.5890224e-01]], dtype=float32)

In [ ]:
test_image_gen.classes

array([0, 0, 0, ..., 1, 1, 1], dtype=int32)

In [ ]:
predictions = pred_probabilities > 0.5

In [ ]:
predictions

array([[False],
       [False],
       [False],
       ...,
       [ True],
       [ True],
       [ True]])

In [ ]:
print(classification_report(test_image_gen.classes,predictions))

              precision    recall  f1-score   support

           0       0.97      0.93      0.95      1000
           1       0.94      0.97      0.95      1000

    accuracy                           0.95      2000
   macro avg       0.95      0.95      0.95      2000
weighted avg       0.95      0.95      0.95      2000



In [ ]:
confusion_matrix(test_image_gen.classes,predictions)

array([[933,  67],
       [ 31, 969]])

In [ ]:
test_dir = '/content/drive/MyDrive/CELLSFINA/TEST'

In [ ]:
test_datagen= ImageDataGenerator(rescale=1./255)
test_generator = test_datagen.flow_from_directory(
    test_dir,
    target_size=(50,50),
    batch_size= 120,
    class_mode='binary')

Found 2000 images belonging to 2 classes.


In [ ]:
mymodel = load_model('/content/model_malaria (1)CRIT.h5')

In [ ]:
from keras.utils import to_categorical
y_test = to_categorical(test_generator.classes)

In [ ]:
y_pred_mymodel = mymodel.predict(test_generator)

17/17 [==============================] - 6s 337ms/step


In [ ]:
y_pred_mymodel = np.argmax(y_pred_mymodel, axis=1)
y_test = np.argmax(y_test, axis=1)

In [ ]:
print(classification_report(y_test, y_pred_mymodel))

              precision    recall  f1-score   support

           0       0.51      0.51      0.51      1000
           1       0.51      0.51      0.51      1000

    accuracy                           0.51      2000
   macro avg       0.51      0.51      0.51      2000
weighted avg       0.51      0.51      0.51      2000

