<a href="https://colab.research.google.com/github/rajma1/Savedmodels/blob/main/CNNmod.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from keras.preprocessing.image import ImageDataGenerator
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report,confusion_matrix

In [ ]:
image_shape = (128,128,3)
batch_size = 16

In [ ]:
test_path = '/content/drive/MyDrive/CELLSFINA/TEST'

In [ ]:
image_generator = ImageDataGenerator(rotation_range=20, # rotate the image 20 degrees
                               width_shift_range=0.10, # Shift the pic width by a max of 5%
                               height_shift_range=0.10, # Shift the pic height by a max of 5%
                               rescale=1/255, # Rescale the image by normalzing it.
                               shear_range=0.1, # Shear means cutting away part of the image (max 10%)
                               zoom_range=0.1, # Zoom in by 10% max
                               horizontal_flip=True, # Allo horizontal flipping
                               fill_mode='nearest' # Fill in missing pixels with the nearest filled value
                              )

In [ ]:
test_image_generator = image_generator.flow_from_directory(test_path,
                                               target_size=image_shape[:2],
                                                color_mode='rgb',
                                               batch_size=batch_size,
                                               class_mode='binary',
                                                shuffle=False)

Found 2000 images belonging to 2 classes.


In [ ]:
from tensorflow.keras.models import load_model
model = load_model('/content/drive/MyDrive/malaria_detector.h5')

In [ ]:
model.evaluate_generator(test_image_generator)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: `Model.evaluate_generator` is deprecated and will be removed in a future version. Please use `Model.evaluate`, which supports generators.
  """Entry point for launching an IPython kernel.


[0.14424839615821838, 0.9514999985694885]

In [ ]:
pred_probabilities = model.predict_generator(test_image_generator)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  """Entry point for launching an IPython kernel.


In [ ]:
pred_probabilities

array([[0.01074447],
       [0.0010921 ],
       [0.00103106],
       ...,
       [0.9947222 ],
       [0.9913228 ],
       [0.9989244 ]], dtype=float32)

In [ ]:
test_image_generator.classes

array([0, 0, 0, ..., 1, 1, 1], dtype=int32)

In [ ]:
predictions = pred_probabilities > 0.5

In [ ]:
predictions

array([[False],
       [False],
       [False],
       ...,
       [ True],
       [ True],
       [ True]])

In [ ]:
test_image_generator.classes

array([0, 0, 0, ..., 1, 1, 1], dtype=int32)

In [ ]:
print(classification_report(test_image_generator.classes,predictions))

              precision    recall  f1-score   support

           0       0.97      0.94      0.96      1000
           1       0.95      0.97      0.96      1000

    accuracy                           0.96      2000
   macro avg       0.96      0.96      0.96      2000
weighted avg       0.96      0.96      0.96      2000



In [ ]:
confusion_matrix(test_image_generator.classes,predictions)

array([[945,  55],
       [ 34, 966]])