<a href="https://colab.research.google.com/github/rajma1/Savedmodels/blob/main/mobilenet111.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import tensorflow 

In [ ]:
model = load_model('/content/drive/MyDrive/mobileNet_malaria_detector.h5')

In [ ]:
test_path = '/content/drive/MyDrive/CELLSFINA/TEST'

In [ ]:
test_batches = ImageDataGenerator(preprocessing_function=tensorflow.keras.applications.mobilenet.preprocess_input).flow_from_directory(
    directory=test_path, target_size=(130,130), batch_size=16, shuffle=False)

Found 2000 images belonging to 2 classes.


In [ ]:
model.evaluate(test_batches)

125/125 [==============================] - 252s 2s/step - loss: 0.0287 - accuracy: 0.9910


[0.02868780680000782, 0.9909999966621399]

In [ ]:
predictions = model.predict_generator(test_batches)

predictions


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  """Entry point for launching an IPython kernel.


array([[9.99988139e-01, 1.18358339e-05],
       [9.99988735e-01, 1.12645475e-05],
       [9.99999464e-01, 5.10165478e-07],
       ...,
       [1.12842445e-05, 9.99988616e-01],
       [5.97579165e-05, 9.99940217e-01],
       [2.99645279e-07, 9.99999583e-01]], dtype=float32)

In [ ]:
import numpy as np

In [ ]:
pred = list(zip(*predictions))[1]
pred = np.array(pred) > 0.5

pred

array([False, False, False, ...,  True,  True,  True])

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(test_batches.classes,pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1000
           1       0.99      0.99      0.99      1000

    accuracy                           0.99      2000
   macro avg       0.99      0.99      0.99      2000
weighted avg       0.99      0.99      0.99      2000



In [ ]:
confusion_matrix(test_batches.classes, pred)

array([[989,  11],
       [  7, 993]])